name: Create SLSA File 2.0
on:
  - workflow_dispatch

permissions: read-all

env:
  GH_TOKEN: ${{ github.token }}
  ISSUE_REPOSITORY: ${{ github.repository }}
jobs:
  usetrw:
    permissions:
      contents: write
      id-token: write
      actions: read   # For the entrypoint.
      packages: write
    uses: AdamKorcz/slsa-github-generator/.github/workflows/builder_maven_slsa3.yml@maven2
  publish:
    needs: [usetrw]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_KEY_PASS
      
          
      - name: Download the target dir
        uses: actions/download-artifact@v3
        with:
          name: target
      - name: Download the slsa attestation
        uses: actions/download-artifact@v3
        with:
          name: slsa-attestations
          path: slsa-attestations
          
      - name: Publish to the Maven Central Repository
        run: |
          ls ..
          ls
          ls slsa-attestations
          cd plugin && mvn clean install && cd ..
          mvn javadoc:jar source:jar
          VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
          FILES=
          TYPES=
          CLASSIFIERS=
          for name in $(find ./ -name test-java-project-$VERSION-*.jar)
          do
            TARGET=$(echo $name | rev | cut -d\- -f1 | rev)
            TYPE=${TARGET##*.}
            CLASSIFIER=${TARGET%.*}
            FILES=$FILES$name,
            TYPES=$TYPES$TYPE,
            CLASSIFIERS=$CLASSIFIERS$CLASSIFIER,
          done
          for name in $(find ./ -name test-java-project-$VERSION-*.jar.intoto.sigstore)
          do
            TARGET=$(echo $name | rev | cut -d\- -f1 | rev)
            CLASSIFIER=${TARGET::-9}
            FILES=$FILES$name,
            TYPES=$TYPES"sigstore,"
            CLASSIFIERS=$CLASSIFIERS$CLASSIFIER,
          done
          FILES=${FILES::-1}
          TYPES=${TYPES::-1}
          CLASSIFIERS=${CLASSIFIERS::-1}
          mvn validate jar:jar -Dfile=target/test-java-project-$VERSION.jar -Durl=https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/ -DrepositoryId=ossrh -Dfiles=$FILES -Dtypes=$TYPES -Dclassifiers=$CLASSIFIERS -DpomFile=pom.xml gpg:sign-and-deploy-file
          curl -X POST -d @slsa-attestations/test-java-project-$VERSION.jar.intoto.sigstore -u "${MAVEN_USERNAME}":"${MAVEN_PASSWORD}" -H "Content-Type:text/plain" -v https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/io/github/adamkorcz/test-java-project/$VERSION/test-java-project-$VERSION.jar.intoto.sigstore
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
