name: Create SLSA File 2.0
on:
  - workflow_dispatch

permissions: read-all

env:
  GH_TOKEN: ${{ github.token }}
  ISSUE_REPOSITORY: ${{ github.repository }}
jobs:
  usetrw:
    permissions:
      contents: write
      id-token: write
      actions: read   # For the entrypoint.
      packages: write
    uses: AdamKorcz/slsa-github-generator/.github/workflows/builder_maven_slsa3.yml@maven2
  publish:
    needs: [usetrw]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_KEY_PASS
      
          
      - name: Download the target dir
        uses: actions/download-artifact@v3
        with:
          name: target
      - name: Download the slsa attestation
        uses: actions/download-artifact@v3
        with:
          name: my-slsa-attestation
          
      - name: Publish to the Maven Central Repository
        run: |
          ls ..
          ls
          cd plugin && mvn clean install && cd ..
          VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout); mvn validate jar:jar javadoc:jar source:jar -Dfile=target/test-java-project-$VERSION.jar -Durl=https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/ -DrepositoryId=ossrh -Dfiles=textfile.txt -Dtypes=txt -Dclassifiers=textfile -Djavadoc=target/test-java-project-$VERSION.jar -Dsources=target/test-java-project-$VERSION-sources.jar -DpomFile=pom.xml gpg:sign-and-deploy-file
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
