name: Create SLSA File
on:
  - workflow_dispatch

permissions: read-all

env:
  GH_TOKEN: ${{ github.token }}
  ISSUE_REPOSITORY: ${{ github.repository }}
jobs:
  usetrw:
    permissions:
      contents: write
      id-token: write
      actions: read   # For the entrypoint.
      packages: write
    uses: AdamKorcz/java-slsa-generator/.github/workflows/create-slsa-file.yml@main
