name: Publish Gradle with action
on:
  - workflow_dispatch

permissions: read-all

env:
  GH_TOKEN: ${{ github.token }}
  ISSUE_REPOSITORY: ${{ github.repository }}
jobs:
  usetrw:
    permissions:
      contents: read
      id-token: write
      actions: read   # For the entrypoint.
      packages: read
    uses: AdamKorcz/slsa-github-generator/.github/workflows/builder_gradle_slsa3.yml@make-gradle-publisher-an-action
    with:
      rekor-log-public: true
      artifact-list: build/libs/test-java-project-0.1.18.jar,build/libs/test-java-project-0.1.18-javadoc.jar,build/libs//test-java-project-0.1.18-sources.jar
  publish:
    runs-on: ubuntu-latest
    needs: usetrw
    permissions:
      contents: read
      id-token: write
      actions: read
    steps:
      - name: publish
        id: publish
        uses: AdamKorcz/slsa-github-generator/actions/gradle/publish@make-gradle-publisher-an-action
        with:
          provenance-download-name: "${{ needs.usetrw.outputs.provenance-download-name }}"
          provenance-download-sha256: "${{ needs.usetrw.outputs.provenance-download-sha256 }}"
          target-download-sha256: "${{ needs.usetrw.outputs.target-download-sha256 }}"
          maven-username: ${{ secrets.OSSRH_USERNAME }}
          maven-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-key-pass: ${{ secrets.GPG_PASSPHRASE }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          jdk-version: "17"
#        secrets:
#          maven-username: ${{ secrets.OSSRH_USERNAME }}
#          maven-password: ${{ secrets.OSSRH_PASSWORD }}
#          gpg-key-pass: ${{ secrets.GPG_PASSPHRASE }}
#          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
